### ISSUE TITLE
Update docstrings for English

### ISSUE THREAD

**Issue by alanjds** [Python-Tools/asyncio-executor#1]
Great job. And very reusable.

However, having the docstrings not in English makes difficult for foreign people to help the project. English is not my natural language, but is very easier to help if documentation is in English.

Thanks.

**Comment by hsz1273327** [comment]
Thank you for so much concern. I'd like to have a documentation in English, but you see my English is very poor.....however I will update it these days.....er....that will be a big project for me....

**Comment by alanjds** [comment]
No problem. Thank you. Your English is very better then my Chinese 👍

**Comment by hsz1273327** [comment]
Submit may be late but will never be absent :joy:
